openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://onlineschool-production.up.railway.app'
paths:
  /api/blogs:
    post:
      summary: 'Show the form for creating a new resource.'
      operationId: showTheFormForCreatingANewResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: esse
                description:
                  type: string
                  description: ''
                  example: sed
              required:
                - title
                - description
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/blogs/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: jmwdentdugu
                description:
                  type: string
                  description: ''
                  example: consequatur
              required:
                - title
                - description
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the blog.'
        example: nisi
        required: true
        schema:
          type: string
  /api/subscribers:
    post:
      summary: 'Show the form for creating a new resource.'
      operationId: showTheFormForCreatingANewResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: casandra.koss@example.net
              required:
                - email
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/subscribers/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: sint
              required:
                - email
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the subscriber.'
        example: qui
        required: true
        schema:
          type: string
  /api/courses:
    post:
      summary: 'Show the form for creating a new resource.'
      operationId: showTheFormForCreatingANewResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: et
                description:
                  type: string
                  description: ''
                  example: necessitatibus
              required:
                - title
                - description
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/courses/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kuwxxurnuhuygkn
                description:
                  type: string
                  description: ''
                  example: neque
              required:
                - title
                - description
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the course.'
        example: sed
        required: true
        schema:
          type: string
  /api/courses_time:
    post:
      summary: 'Show the form for creating a new resource.'
      operationId: showTheFormForCreatingANewResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_id:
                  type: string
                  description: ''
                  example: animi
                courseMonth:
                  type: string
                  description: ''
                  example: possimus
                start_time:
                  type: string
                  description: ''
                  example: sed
                end_time:
                  type: string
                  description: ''
                  example: commodi
                day_of_month:
                  type: string
                  description: ''
                  example: tempore
              required:
                - course_id
                - courseMonth
                - start_time
                - end_time
                - day_of_month
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/courses_time/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the courses time.'
        example: dolor
        required: true
        schema:
          type: string
  /api/guest_users:
    post:
      summary: 'Show the form for creating a new resource.'
      operationId: showTheFormForCreatingANewResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                courseId:
                  type: string
                  description: ''
                  example: porro
                firstName:
                  type: string
                  description: ''
                  example: voluptate
                lastName:
                  type: string
                  description: ''
                  example: quae
                age:
                  type: string
                  description: ''
                  example: laborum
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: hauck.neva@example.com
              required:
                - courseId
                - firstName
                - lastName
                - age
                - email
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: consequatur
              required:
                - id
      security: []
  '/api/guest_users/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                courseId:
                  type: string
                  description: ''
                  example: aut
                firstName:
                  type: string
                  description: ''
                  example: corporis
                lastName:
                  type: string
                  description: ''
                  example: corrupti
                age:
                  type: string
                  description: ''
                  example: voluptatum
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: elmore45@example.net
              required:
                - courseId
                - firstName
                - lastName
                - age
                - email
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the guest user.'
        example: non
        required: true
        schema:
          type: string
  /api/free_lessons:
    post:
      summary: 'Show the form for creating a new resource.'
      operationId: showTheFormForCreatingANewResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: ''
                  example: 2
                courseId:
                  type: integer
                  description: ''
                  example: 7
                numberOfMonth:
                  type: integer
                  description: ''
                  example: 4
                dayOfMonth:
                  type: integer
                  description: ''
                  example: 11
                startTime:
                  type: string
                  description: 'Must be a valid date in the format <code>H:i:s</code>.'
                  example: '19:19:51'
                endTime:
                  type: string
                  description: 'Must be a valid date in the format <code>H:i:s</code>.'
                  example: '19:19:51'
              required:
                - userId
                - courseId
                - numberOfMonth
                - dayOfMonth
                - startTime
                - endTime
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: consequatur
              required:
                - id
      security: []
  '/api/free_lessons/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numberOfMonth:
                  type: string
                  description: ''
                  example: aliquid
                dayOfMonth:
                  type: string
                  description: ''
                  example: temporibus
                startTime:
                  type: string
                  description: ''
                  example: eum
                endTime:
                  type: string
                  description: ''
                  example: commodi
                meetUrl:
                  type: string
                  description: ''
                  example: possimus
              required:
                - numberOfMonth
                - dayOfMonth
                - startTime
                - endTime
                - meetUrl
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the free lesson.'
        example: pariatur
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
